name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Vet
      run: go vet ./deque/...

    - name: Build
      run: go build -v ./deque/...

    - name: Test
      run: go test -race -v ./deque/... -coverprofile=coverage_deque.txt -covermode=atomic

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: coverage.txt
